test_lua = class({})
LinkLuaModifier( "modifier_test", "lua_abilities/test/modifier_test", LUA_MODIFIER_MOTION_NONE )

--------------------------------------------------------------------------------
-- Passive Modifier
function test_lua:GetIntrinsicModifierName()
	return "modifier_test"
end

--[[
Invoking results:
[none]
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC
MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE

[loop]
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE
MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE
MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE
MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE

[attack begin animation]
MODIFIER_EVENT_ON_ATTACK_START
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT
MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE
MODIFIER_PROPERTY_PRE_ATTACK

[projectile launched]
MODIFIER_EVENT_ON_ATTACK

[attacker finish animation]
MODIFIER_EVENT_ON_ATTACK_FINISHED

[projectile reached]
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE
MODIFIER_PROPERTY_PROCATTACK_FEEDBACK
MODIFIER_EVENT_ON_ATTACK_LANDED
MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE
MODIFIER_EVENT_ON_TAKEDAMAGE

[projectile missed]
MODIFIER_EVENT_ON_ATTACK_FAIL
]]
